---

- hosts: localhost
  tasks:
    - name: Check File
      shell: ls -ld /etc/
      register: result  
      ignore_errors: yes

    - debug:
        msg: "{{ result }}"

    - name: Define Variable
      set_fact:
         exists: "{{ result.stdout }}"
      when: result|success

    - name: Display Variable
      debug: msg="{{ exists }}"
      ignore_errors: yes 
